# whitelist.conf - Rules for Mini AI VPN Gateway whitelist
# Bỏ qua kiểm tra cho các IP, dải mạng CIDR và Tên miền tin cậy dưới đây.
# Định dạng: Mỗi dòng một luật, dòng bắt đầu bằng '#' sẽ được coi là comment.

# 1. Các máy chủ DNS công cộng tin cậy
8.8.8.8 # (DNS của Google)
1.1.1.1 # (DNS của Cloudflare)

# 2. Dải mạng nội bộ an toàn (WireGuard VPN clients và Loopback)
127.0.0.1 # IP chỉ chính nó, phục vụ giao tiếp nội bộ trong Server (Địa chỉ Loopback)
#10.38.50.1
#10.38.50.2
#10.0.0.0/8
10.38.50.99 # IP tin cay gia lap mau cho Demo 5 (Nam trong dai mang VPN de luon di qua VPN)

# 3. Tên miền tin cậy cơ bản (Được cấp phép truy cập không kiểm duyệt)
google.com
wikipedia.org
microsoft.com
apple.com
github.com
facebook.com
twitter.com

# 4. Tên miền mở rộng (Wildcard) - Tương đương với tổ chức (Organization) trong Slips
*.google.com
*.wikipedia.org
*.microsoft.com  # Bao gồm teams.microsoft.com, login.microsoft.com...
*.apple.com
*.github.com
*.facebook.com
*.twitter.com
*.skype.com      # Microsoft Teams/Skype services
*.office.com     # Microsoft Office 365 services
*.windowsupdate.com # Dịch vụ cập nhật của Windows

# 5. Các tên miền đặc thù phục vụ hệ thống IDS (Lấy từ bộ Whitelist gốc của Stratosphere IPS)
useragentstring.com
macvendorlookup.com
maclookup.app
ip-api.com
asnlookup.com
ipinfo.io
virustotal.com
cymru.com
spamhaus.org
circl.lu
check.torproject.org
cert.pl
abuse.ch
whois.namecheap.com
whois.verisign-grs.com
rdap.arin.net
whois.arin.net
rdap.pacloudflare.com
whois.pir.org
macvendors.com
rdap.apnic.net.cdn.cloudflare.net
whois.name.com
ripe.net
dblb-3.db.ripe.net
whois.us-west-2.pirproda.registry-upper.dnts.net
reputation.alienvault.com
lists.blocklist.de
osint.digitalside.it
repsh.liberouter.org
nerd.cesnet.cz
whois.eu
whois.registrar.amazon.com
whois.nic.it
tranco-list.eu
rules.emergingthreats.net
digicert.com
markmonitor.com
whois.nic.co
